sudo: require
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"
script: 
    - mkdir bin
    - g++ -v
    - ln -s /usr/bin/g++-7 /usr/local/bin/g++
    - g++ -v
    - make && make test
